# Generated by Django 4.1.13 on 2024-04-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FashionApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('article_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_code', models.CharField(max_length=100)),
                ('prod_name', models.CharField(max_length=500)),
                ('product_type_no', models.IntegerField()),
                ('product_type_name', models.CharField(max_length=500)),
                ('product_group_name', models.CharField(max_length=500)),
                ('graphical_appearance_no', models.IntegerField()),
                ('graphical_appearance_name', models.CharField(max_length=500)),
                ('colour_group_code', models.IntegerField()),
                ('colour_group_name', models.CharField(max_length=500)),
                ('perceived_colour_value_id', models.IntegerField()),
                ('perceived_colour_value_name', models.CharField(max_length=500)),
                ('perceived_colour_master_id', models.IntegerField()),
                ('perceived_colour_master_name', models.CharField(max_length=500)),
                ('department_no', models.IntegerField()),
                ('department_name', models.CharField(max_length=500)),
                ('index_code', models.CharField(max_length=100)),
                ('index_name', models.CharField(max_length=500)),
                ('index_group_no', models.IntegerField()),
                ('index_group_name', models.CharField(max_length=500)),
                ('section_no', models.IntegerField()),
                ('section_name', models.CharField(max_length=500)),
                ('garment_group_no', models.IntegerField()),
                ('garment_group_name', models.CharField(max_length=500)),
                ('detail_desc', models.TextField()),
            ],
        ),
    ]
